version: '3.2'
services:
  app:
    container_name: app
    image: regis/msse661:production
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - type:   volume
        source: mysqlvol
        target: /var/lib/mysql
        volume:
          nocopy: true

volumes:
  mysqlvol:
