version: '3.2'
services:
  app:
    ports:
      - 8888:80
    volumes:
      - type:   bind
        source: ./public_html
        target: /var/www/html
    environment:
      DB_HOST:      mysql
      DB_DATABASE:  baom
      DB_USERNAME:  baom
      DB_PASSWORD:  password

  mysql:
    environment:
      MYSQL_DATABASE:       baom
      MYSQL_USER:           baom
      MYSQL_PASSWORD:       password
      MYSQL_ROOT_PASSWORD:  password

  ftp:
    container_name: ftp
    image: bogem/ftp
    ports:
      - '20:20'
      - '21:21'
      - '47400-47470:47400-47470'
    volumes:
      - type:   bind
        source: ./public_html
        target: /home/vsftpd
    environment:
      FTP_USER: Regis
      FTP_PASS: Regis123
      PASV_ADDRESS:

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.8
    links:
      - mysql:mysql
    ports:
      - 8181:80
    environment:
      PMA_HOST:             mysql
      MYSQL_USERNAME:       root
      MYSQL_ROOT_PASSWORD:  password

volumes:
  htmldata: