version: '3.2'
services:
  app:
    image: regis/msse661:dev
    ports:
      - 8888:80
      - 9999:9000
    volumes:
      - type:   bind
        source: ./html
        target: /var/www/html
      - type:   bind
        source: ./webapp/config
        target: /var/www/webapp/config
      - type:   bind
        source: ./webapp/src
        target: /var/www/webapp/src
      - type:   bind
        source: ./webapp/phpunit.xml
        target: /var/www/webapp/phpunit.xml
      - type:   bind
        source: ./webapp/unittest
        target: /var/www/webapp/unittest
    env_file:
      - development.env

  mysql:
    env_file:
      - development.env

#  ftp:
#    container_name: ftp
#    image: bogem/ftp
#    ports:
#      - '20:20'
#      - '21:21'
#      - '47400-47470:47400-47470'
#    volumes:
#      - type:   bind
#        source: ./html
#        target: /home/vsftpd
#    env_file:
#      - development.env
#    environment:
#      PASV_ADDRESS:

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.8
    links:
      - mysql:mysql
    ports:
      - 8181:80
    env_file:
      - development.env

volumes:
  htmldata: